### ISSUE TITLE
Error running from cmdline

### ISSUE THREAD

**Issue by billdunk** [SillyGoat/teslacam#1]
E:\tesla\teslacam\sentryClips\2020-04-14_18-35-43\event.json: Invalid data found when processing input
process <Process 21800> failed
skip problematic video E:\tesla\teslacam\sentryClips\2020-04-14_18-35-43\event.json
cancel outstanding tasks
cancelling 1326 outstanding tasks
tasks cancelled
...
  File "C:\Users\bill\AppData\Local\Programs\Python\Python39\lib\site-packages\teslacam\extract.py", line 75, in populate_video_map
    video_file_prefix = match_result.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by SillyGoat** [comment]
I was able to reproduce the problem and apply a fix.  Please see how it works for you.  Thanks

**Comment by billdunk** [comment]
It is working.  Thanks
